---
title: "Lineamientos para el primer trabajo - TAE"
author: Prof. Juan David Ospina Arango</br>Universidad Nacional - Sede Medellín</br>Técnicas
  de aprendizaje estadístico</br>Semestre 2019-02
output:
  html_document:
    df_print: paged
  word_document: default
---

# Agrupamiento de los barrios de Medellín
En este trabajo se abordará el problema de agrupar los barrios de Medellín de acuerdo a distintas dimensiones y analizar espacialmente las agrupaciones.

El insumo principal de este trabajo son los [datos abiertos del portal Medata](http://medata.gov.co) y en particular la [Encuesta de Calidad de Vida Medellín Cómo vamos](http://medata.gov.co/dataset/encuesta-calidad-de-vida).



## 1 - Caracterización de las dimensiones
Los microdatos de la encuesta (las filas), representan las respuestas de los encuestados a una serie de preguntas. Estas se pueden agrupar en dimensiones como salud, educación, calidad de la vivienda, etc. El trabajo debe definir claramente las dimensiones con las que caracterizará a los barrios de Medellín y las preguntas que conformarán cada dimensión. La forma en que las respuestas a las preguntas se consolidan para conformar las dimensiones hacen parte del trabajo.

## 2 - Agrupamiento
Utilizando las variables construidas en cada dimensión se debe llevar a cabo un análisis de agrupamiento utilizando las técnicas vistas en el curso (agrupamiento jerárquico y K-Medias) u otras técnicas debidamente descritas y referenciadas.

## 3 - Análisis espacial
Los grupos obtenidos se deben representar en el mapa de Medellín y a partir de lo observado concluir sobre la distribución espacial de las características que conforman los grupos.

## 4 - Reporte 
El trabajo se debe entregar en un reporte que contenga la descripción del trabajo, la construcción de las dimensiones y su motivación, la construcción de los grupos, el análisis espacial, las fuentes bibliográficas, las conclusiones identificadas y las propuestas de continuación del trabajo.

El código debe estar en un repositorio de GitHub y debe ser accesible para ser revisado.



## 5 - Equipos y fecha de entrega
1. Equipos: los equipos estarán conformados por cuatro o cinco estudiantes. Cada equipo deberá tener al menos un estudiante del pregrado en estadística y al menos un estudiante del pregrado e ingeniería de sistemas.

2. Fecha de entrega: el trabajo se deberá entregar el día miércoles 19 de febrero y se debe enviar al correo jdospina@unal.edu.co.










